language: generic 
sudo: required
services:
    - docker

before_install:
    - docker-compose up --build

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "samepage"
    env: "Samepage-env"
    bucket: "elasticbeanstalk-us-east-1-400418324967"
    bucket_path: "samepage"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
s       secure: "$AWS_SECRET_KEY"